//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscoLights.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Images {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscoLights.Properties.Images", typeof(Images).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon AmberOff {
            get {
                object obj = ResourceManager.GetObject("AmberOff", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AmberOffX128 {
            get {
                object obj = ResourceManager.GetObject("AmberOffX128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AmberOffX16 {
            get {
                object obj = ResourceManager.GetObject("AmberOffX16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AmberOffX256 {
            get {
                object obj = ResourceManager.GetObject("AmberOffX256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AmberOffX32 {
            get {
                object obj = ResourceManager.GetObject("AmberOffX32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AmberOffX48 {
            get {
                object obj = ResourceManager.GetObject("AmberOffX48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AmberOffX64 {
            get {
                object obj = ResourceManager.GetObject("AmberOffX64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon AmberOn {
            get {
                object obj = ResourceManager.GetObject("AmberOn", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AmberOnX128 {
            get {
                object obj = ResourceManager.GetObject("AmberOnX128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AmberOnX16 {
            get {
                object obj = ResourceManager.GetObject("AmberOnX16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AmberOnX256 {
            get {
                object obj = ResourceManager.GetObject("AmberOnX256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AmberOnX32 {
            get {
                object obj = ResourceManager.GetObject("AmberOnX32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AmberOnX48 {
            get {
                object obj = ResourceManager.GetObject("AmberOnX48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AmberOnX64 {
            get {
                object obj = ResourceManager.GetObject("AmberOnX64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon BlueOff {
            get {
                object obj = ResourceManager.GetObject("BlueOff", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueOffX128 {
            get {
                object obj = ResourceManager.GetObject("BlueOffX128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueOffX16 {
            get {
                object obj = ResourceManager.GetObject("BlueOffX16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueOffX256 {
            get {
                object obj = ResourceManager.GetObject("BlueOffX256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueOffX32 {
            get {
                object obj = ResourceManager.GetObject("BlueOffX32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueOffX48 {
            get {
                object obj = ResourceManager.GetObject("BlueOffX48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueOffX64 {
            get {
                object obj = ResourceManager.GetObject("BlueOffX64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon BlueOn {
            get {
                object obj = ResourceManager.GetObject("BlueOn", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueOnX128 {
            get {
                object obj = ResourceManager.GetObject("BlueOnX128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueOnX16 {
            get {
                object obj = ResourceManager.GetObject("BlueOnX16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueOnX256 {
            get {
                object obj = ResourceManager.GetObject("BlueOnX256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueOnX32 {
            get {
                object obj = ResourceManager.GetObject("BlueOnX32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueOnX48 {
            get {
                object obj = ResourceManager.GetObject("BlueOnX48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueOnX64 {
            get {
                object obj = ResourceManager.GetObject("BlueOnX64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon GreenOff {
            get {
                object obj = ResourceManager.GetObject("GreenOff", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenOffX128 {
            get {
                object obj = ResourceManager.GetObject("GreenOffX128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenOffX16 {
            get {
                object obj = ResourceManager.GetObject("GreenOffX16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenOffX256 {
            get {
                object obj = ResourceManager.GetObject("GreenOffX256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenOffX32 {
            get {
                object obj = ResourceManager.GetObject("GreenOffX32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenOffX48 {
            get {
                object obj = ResourceManager.GetObject("GreenOffX48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenOffX64 {
            get {
                object obj = ResourceManager.GetObject("GreenOffX64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon GreenOn {
            get {
                object obj = ResourceManager.GetObject("GreenOn", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenOnX128 {
            get {
                object obj = ResourceManager.GetObject("GreenOnX128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenOnX16 {
            get {
                object obj = ResourceManager.GetObject("GreenOnX16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenOnX256 {
            get {
                object obj = ResourceManager.GetObject("GreenOnX256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenOnX32 {
            get {
                object obj = ResourceManager.GetObject("GreenOnX32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenOnX48 {
            get {
                object obj = ResourceManager.GetObject("GreenOnX48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenOnX64 {
            get {
                object obj = ResourceManager.GetObject("GreenOnX64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon RedOff {
            get {
                object obj = ResourceManager.GetObject("RedOff", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedOffX128 {
            get {
                object obj = ResourceManager.GetObject("RedOffX128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedOffX16 {
            get {
                object obj = ResourceManager.GetObject("RedOffX16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedOffX256 {
            get {
                object obj = ResourceManager.GetObject("RedOffX256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedOffX32 {
            get {
                object obj = ResourceManager.GetObject("RedOffX32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedOffX48 {
            get {
                object obj = ResourceManager.GetObject("RedOffX48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedOffX64 {
            get {
                object obj = ResourceManager.GetObject("RedOffX64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon RedOn {
            get {
                object obj = ResourceManager.GetObject("RedOn", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedOnX128 {
            get {
                object obj = ResourceManager.GetObject("RedOnX128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedOnX16 {
            get {
                object obj = ResourceManager.GetObject("RedOnX16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedOnX256 {
            get {
                object obj = ResourceManager.GetObject("RedOnX256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedOnX32 {
            get {
                object obj = ResourceManager.GetObject("RedOnX32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedOnX48 {
            get {
                object obj = ResourceManager.GetObject("RedOnX48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedOnX64 {
            get {
                object obj = ResourceManager.GetObject("RedOnX64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon UltravioletOff {
            get {
                object obj = ResourceManager.GetObject("UltravioletOff", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UltravioletOffX128 {
            get {
                object obj = ResourceManager.GetObject("UltravioletOffX128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UltravioletOffX16 {
            get {
                object obj = ResourceManager.GetObject("UltravioletOffX16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UltravioletOffX256 {
            get {
                object obj = ResourceManager.GetObject("UltravioletOffX256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UltravioletOffX32 {
            get {
                object obj = ResourceManager.GetObject("UltravioletOffX32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UltravioletOffX48 {
            get {
                object obj = ResourceManager.GetObject("UltravioletOffX48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UltravioletOffX64 {
            get {
                object obj = ResourceManager.GetObject("UltravioletOffX64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon UltravioletOn {
            get {
                object obj = ResourceManager.GetObject("UltravioletOn", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UltravioletOnX128 {
            get {
                object obj = ResourceManager.GetObject("UltravioletOnX128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UltravioletOnX16 {
            get {
                object obj = ResourceManager.GetObject("UltravioletOnX16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UltravioletOnX256 {
            get {
                object obj = ResourceManager.GetObject("UltravioletOnX256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UltravioletOnX32 {
            get {
                object obj = ResourceManager.GetObject("UltravioletOnX32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UltravioletOnX48 {
            get {
                object obj = ResourceManager.GetObject("UltravioletOnX48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UltravioletOnX64 {
            get {
                object obj = ResourceManager.GetObject("UltravioletOnX64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon WhiteOff {
            get {
                object obj = ResourceManager.GetObject("WhiteOff", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhiteOffX128 {
            get {
                object obj = ResourceManager.GetObject("WhiteOffX128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhiteOffX16 {
            get {
                object obj = ResourceManager.GetObject("WhiteOffX16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhiteOffX256 {
            get {
                object obj = ResourceManager.GetObject("WhiteOffX256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhiteOffX32 {
            get {
                object obj = ResourceManager.GetObject("WhiteOffX32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhiteOffX48 {
            get {
                object obj = ResourceManager.GetObject("WhiteOffX48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhiteOffX64 {
            get {
                object obj = ResourceManager.GetObject("WhiteOffX64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon WhiteOn {
            get {
                object obj = ResourceManager.GetObject("WhiteOn", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhiteOnX128 {
            get {
                object obj = ResourceManager.GetObject("WhiteOnX128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhiteOnX16 {
            get {
                object obj = ResourceManager.GetObject("WhiteOnX16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhiteOnX256 {
            get {
                object obj = ResourceManager.GetObject("WhiteOnX256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhiteOnX32 {
            get {
                object obj = ResourceManager.GetObject("WhiteOnX32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhiteOnX48 {
            get {
                object obj = ResourceManager.GetObject("WhiteOnX48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhiteOnX64 {
            get {
                object obj = ResourceManager.GetObject("WhiteOnX64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon YellowOff {
            get {
                object obj = ResourceManager.GetObject("YellowOff", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowOffX128 {
            get {
                object obj = ResourceManager.GetObject("YellowOffX128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowOffX16 {
            get {
                object obj = ResourceManager.GetObject("YellowOffX16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowOffX256 {
            get {
                object obj = ResourceManager.GetObject("YellowOffX256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowOffX32 {
            get {
                object obj = ResourceManager.GetObject("YellowOffX32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowOffX48 {
            get {
                object obj = ResourceManager.GetObject("YellowOffX48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowOffX64 {
            get {
                object obj = ResourceManager.GetObject("YellowOffX64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon YellowOn {
            get {
                object obj = ResourceManager.GetObject("YellowOn", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowOnX128 {
            get {
                object obj = ResourceManager.GetObject("YellowOnX128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowOnX16 {
            get {
                object obj = ResourceManager.GetObject("YellowOnX16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowOnX256 {
            get {
                object obj = ResourceManager.GetObject("YellowOnX256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowOnX32 {
            get {
                object obj = ResourceManager.GetObject("YellowOnX32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowOnX48 {
            get {
                object obj = ResourceManager.GetObject("YellowOnX48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowOnX64 {
            get {
                object obj = ResourceManager.GetObject("YellowOnX64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
