//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneIDTrimmer.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZoneIDTrimmer.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close when finished.
        /// </summary>
        internal static string CloseWhenFinished {
            get {
                return ResourceManager.GetString("CloseWhenFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing in {0} seconds....
        /// </summary>
        internal static string ClosingIn {
            get {
                return ResourceManager.GetString("ClosingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string CommandClose {
            get {
                return ResourceManager.GetString("CommandClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Donate.
        /// </summary>
        internal static string CommandDonate {
            get {
                return ResourceManager.GetString("CommandDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished..
        /// </summary>
        internal static string DetailsFinish {
            get {
                return ResourceManager.GetString("DetailsFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string DetailsInit {
            get {
                return ResourceManager.GetString("DetailsInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details....
        /// </summary>
        internal static string DetailsLinkDisabled {
            get {
                return ResourceManager.GetString("DetailsLinkDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot;&gt;More details...&lt;/a&gt;.
        /// </summary>
        internal static string DetailsLinkEnabled {
            get {
                return ResourceManager.GetString("DetailsLinkEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        internal static string DetailsStart {
            get {
                return ResourceManager.GetString("DetailsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit &lt;a href=&quot;{0}&quot;&gt;Gasanov.net&lt;/a&gt; for more stuff..
        /// </summary>
        internal static string HomepageLink {
            get {
                return ResourceManager.GetString("HomepageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished. See details below..
        /// </summary>
        internal static string StatusFinish {
            get {
                return ResourceManager.GetString("StatusFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing... Please wait..
        /// </summary>
        internal static string StatusInit {
            get {
                return ResourceManager.GetString("StatusInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working... It may take a while..
        /// </summary>
        internal static string StatusStart {
            get {
                return ResourceManager.GetString("StatusStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored: {0} folders, {1} files
        ///Scanned: {2} folders, {3} files
        ///Trimmed: {4} folders, {5} files
        ///Failed: {6} folders, {7} files.
        /// </summary>
        internal static string TotalInfo {
            get {
                return ResourceManager.GetString("TotalInfo", resourceCulture);
            }
        }
    }
}
